### ISSUE TITLE
Crash with ActivityNotFoundException on clicking a link in a message

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#263]
I got this report, and a comment from a User that this message causes that crash: https://identi.ca/debian/note/ZOn34HSJQ3isbFkDG-W8aw

```
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=17.1
BRAND=motorola
PHONE_MODEL=Moto G
CUSTOM_DATA=
STACK_TRACE=android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=The installation system now installs systemd as the default init system but you can use sysvinit. https://wiki.debian.org/systemd (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1640)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
at android.app.Activity.startActivityForResult(Activity.java:3475)
at android.app.Activity.startActivityForResult(Activity.java:3436)
at android.app.Activity.startActivity(Activity.java:3678)
at android.app.Activity.startActivity(Activity.java:3646)
at android.text.style.URLSpan.onClick(URLSpan.java:62)
at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
at android.widget.TextView.onTouchEvent(TextView.java:7713)
at android.view.View.dispatchTouchEvent(View.java:7713)
...
```
My first search led me to this question: http://stackoverflow.com/questions/14796446/how-to-catch-an-exception-activitynotfoundexception-while-using-linkmovementme
So this looks like a bug in Android firmware. But we need to handle it gracefully anyway...

**Comment by yvolk** [comment]
As I don't see any code of AndStatus in the stack trace, I don't think we can catch the exception
