### ISSUE TITLE
Crash on java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#281]
We received the Crash report from a User. AndStatus should handle this system exception, delaying start of a new Executor...

ANDROID_VERSION=4.4.4
APP_VERSION_NAME=17.1
BRAND=Samsung
PHONE_MODEL=GT-I9100
CUSTOM_DATA=
STACK_TRACE=java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@41e9c110 rejected from java.util.concurrent.ThreadPoolExecutor@41d96598[Running, pool size = 5, active threads = 5, queued tasks = 128, completed tasks = 2]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
at org.andstatus.app.service.MyService.startExecutor(MyService.java:409)
at org.andstatus.app.service.MyService.startExecution(MyService.java:386)
at org.andstatus.app.service.MyService.startStopExecution(MyService.java:307)
at org.andstatus.app.service.MyService.access$1600(MyService.java:51)
at org.andstatus.app.service.MyService$HeartBeat.onProgressUpdate(MyService.java:919)
at org.andstatus.app.service.MyService$HeartBeat.onProgressUpdate(MyService.java:868)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:648)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)

**Comment by yvolk** [comment]
I already received something like this once in two months, see e.g. https://github.com/andstatus/andstatus/issues/281
but only today I realised that the crash itself is only a consequence of a real problem: a lot of "tasks" in the execution queue:
```
STACK_TRACE=java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$SerialExecutor$1@562da5b rejected from java.util.concurrent.ThreadPoolExecutor@1cc5c012
[Running, pool size = 5, active threads = 5, queued tasks = 128, completed tasks = 771]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
at android.os.AsyncTask$SerialExecutor.scheduleNext(AsyncTask.java:244)
```
I will add some monitoring means to find out, what are these tasks that are polluting the queue, and then will decide, how to fix this.

**Comment by yvolk** [comment]
AndStatus v.22.6 with fixes and improved monitoring (to help find a cause of this RejectedExecutionException crash) published to the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app at test it!

**Comment by yvolk** [comment]
I launched AndStatus 22.6 on my old Nexus One with Android 4.4. and it quite easily showed me the the problem. The device uses only 2 active threads, and both of them are occupied by long background processes.
And there are lots of "ShowSyncing" tasks - async indicator, which fills the queue...

```
java.util.concurrent.ThreadPoolExecutor@41b301f0[Running, pool size = 2, active threads = 2, queued tasks = 84, completed tasks = 363] 
Running tasks: 268 sec: HeartBeat [id=240, since=268sec, iteration=1]
256 sec: HeartBeat [id=248, since=256sec, iteration=23]
256 sec: QueueExecutor:{started:4 minutes ago,currentlyExecuting:CommandData:{command:fetch-avatar,created:3 minutes ago,itemId:57,hashCode:48629428,CommandResult:{}},since:just now,status:RUNNING}
256 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41fdd318
256 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41b6c9a8
256 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41e87148
256 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41eabfd0
12 sec: AsyncLoader; RUNNING, since=12, 
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41fc6d20
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41ddf440
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41d839d0
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41eae6e0
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41c950f0
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41b22518
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@41f1fcc8
12 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@42189498
11 sec: ShowSyncing org.andstatus.app.msg.TimelineActivity$5@4205aca0
...
```

**Comment by yvolk** [comment]
The issue fixed by creating several execution pools for different types of tasks.
