### ISSUE TITLE
Support Hubzilla?

### ISSUE THREAD

**Issue by kenrestivo** [andstatus/andstatus#294]
Any plans to allow connecting to Hubzilla? 

https://github.com/redmatrix/hubzilla

It uses a superset of the Twitter and GNUSocial APIs:

https://github.com/redmatrix/hubzilla/blob/master/doc/api_functions.bb

**Comment by yvolk** [comment]
The reason "Hubzilla" or  "Redmatrix" whatever is not (godd enough) supported is simple: there is no active user/tester/developer, who is willing to spend their time on helping me in this:
1. Figure out what already works and what doesn't.
2. Find detailed developer-level information on a proper API to use in every case of incompatibility. 
3. Test intermediate builds of AndStatus.
...

?!

**Comment by kenrestivo** [comment]
This seems sensible. Their API is not fully documented, nor are there functional/unit tests for it in their codebase. Each of those might be large efforts and I'm not sure I'm willing to take those on. 

However, their docs claim to support the Twitter API fully. I'd be willing to experiment and test a branch of AndStatus, and find and possibly fix bugs, if you were interested in adding a UI option to support specifying a Hubzilla endpoint using the Twitter API. 

I'm not familiar with your codebase, but I am familiar with Android development, and I can do builds and submit pull requests.

**Comment by annando** [comment]
Instead of doing changes in AndStatus that would break compatibility to other networks I would suggest to improve the API of Hubzilla. 

However: If it is a change that only improves the "user experience" (like choosing "public" or "non public" for a new post) I would welcome it.

**Comment by yvolk** [comment]
@kenrestivo So we are talking about Twitter API?!
Actually AndStatus currently supports two "dialects" of this API ("Types of Social Network"):
1. Twitter - compatible with today's Twitter API
2. GNU Social - a fork of some older version of Twitter API with several extensions. 

Go to Settings -> Accounts -> Manage Social Networks and add a new system for "Hubzilla", selecting one of the two above types.  Type any URL (Host) of the system... and try!

**Comment by annando** [comment]
@yvolk Hubzilla is the successor of RedMatrix which is a fork of Friendica. It *could* work with the GNU Social part of AndStatus. But since the fork was made *before* I did many changes to the API of Friendica, to support AndStatus, there could be several problems. (If nobody did similar changes to the API of Hubzilla as well)

**Comment by morphtown** [comment]
Am 25.09.2015 um 15:08 schrieb Michael Vogel:
>
> @yvolk <https://github.com/yvolk> Hubzilla is the successor of
> RedMatrix which is a fork of Friendica. It /could/ work with the GNU
> Social part of AndStatus. But since the fork was made /before/ I did
> many changes to the API of Friendica, to support AndStatus, there
> could be several problems. (If nobody did similar changes to the API
> of Hubzilla as well)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andstatus/andstatus/issues/294#issuecomment-143216639>.
>
After they supplied a patch for redmatrix it worked quite well. So it
should with hubzilla. Isn't it just a name change of the project?
Currently I don't have an account because I stupidly missed moving my
identity before parlementum.net's shutdown. Considering to go on with an
own instance in the future.

**Comment by annando** [comment]
Hubzilla is a fork of RedMatrix. It is intended that RedMatrix will be discontinued after Hubzilla is out of its alpha state. If there was a patch for Redmatrix to support AndStatus it will work with Hubzilla for sure.

**Comment by kenrestivo** [comment]
Fantastic, I will try the Manage Social Networks feature, add my Hubzilla account, and try it out!

For future reference, is there a link to the patch which added the RedMatrix support? Indeed, if AndStatus already supports RedMatrix then this should just work.

I have a build system and debugger set up for AndStatus, so if anything goes sideways I'll try to fix/patch it.

**Comment by kenrestivo** [comment]
I tried it, the basic read and post features work. Predictably there are a few issues, i.e.

```
2015-09-25-13-41-03 I/MySimpleCursorAdapter: Ignoring getItemId
2015-09-25-13-41-30 E/CommandExecutorOther: getStatus 0, 
Status code=OK; soft; 
HttpReadResult: getJsonObject; ; statusCode:OK (200); url:'http://redacted.com/api/statuses/show.json?id=0'; authenticated; response:'null'; 
Caused by org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject, 
bogus/hubzilla, 
org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:159)
	at org.json.JSONObject.<init>(JSONObject.java:172)
	at org.andstatus.app.net.http.HttpReadResult.innerGetJsonObject(HttpReadResult.java:138)
	at org.andstatus.app.net.http.HttpReadResult.getJsonObject(HttpReadResult.java:128)
	at org.andstatus.app.net.http.HttpConnection.getRequest(HttpConnection.java:97)
	at org.andstatus.app.net.social.ConnectionTwitter.getMessage1(ConnectionTwitter.java:178)
	at org.andstatus.app.net.social.Connection.getMessage(Connection.java:282)
	at org.andstatus.app.service.CommandExecutorOther.getStatus(CommandExecutorOther.java:292)
	at org.andstatus.app.service.CommandExecutorOther.execute(CommandExecutorOther.java:70)
	at org.andstatus.app.service.CommandExecutorStrategy.executeCommand(CommandExecutorStrategy.java:37)
	at org.andstatus.app.service.MyService$QueueExecutor.doInBackground(MyService.java:645)
	at org.andstatus.app.service.MyService$QueueExecutor.doInBackground(MyService.java:611)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Class null null2015-09-25-13-41-35 I/MySimpleCursorAdapter: Ignoring getItemId
```

But, I'll trace stuff and try to figure out what's going on. If I fix anything I'll send a pull.

**Comment by kenrestivo** [comment]
@morphtown Where might I find this patch?

@yvolk So far, in my personal and unscientific testing, features that work with Hubzilla out-of-the-box using the GNUSocial/StatusNet API:
- Basic timeline reading/syncing
- Reply to a post and having it show up as a child of the parent post
- Posting a new post
- Receiving direct messages (though it is sometimes difficult to find them in the UI)
- Notifications for @ mentions and direct messages

Features which do not work (unclear why):
- Posting a picture or attachment
- Replying to or sending a Direct Message

If there were a client-side functional test suite for the GNU Social API I could point it at a Hubzilla node and verify/test their compliance with the API.

Hubzilla supports additional features but it be best to get the standards implementations sorted out first.

I'd love to see this patch that's been discussed.

**Comment by yvolk** [comment]
@kenrestivo Thank you for testing. 
1. Regarding picture attachment, it could be broken by this new bug #304. I will fix it shortly. 
2. Direct messages and replies to Direct messages are a long and a separate story. Please read it and discuss here: #181

**Comment by kenrestivo** [comment]
The picture attachment problem is reported thusly:

```log4j
        2015-11-16-21-07-56 V/HttpReadResult: ; statusCode:OK (200); url:'https://hub.spaz.org/api/statuses/update.json'; authenticated; posted:'{"media_part_name":"media","source":"AndStatus","status":"Test","media_part_uri":"content:\/\/org.andstatus.app.data.FileProvider\/downloadfile\/1447734941603_11"}'
        2015-11-16-21-07-56 D/CommandExecutorOther: Executed CommandExecutionContext:{MyAccount:{accountName:bamfic/hubzilla,id:11,oid:2,credentialsPresent,syncFrequency:900,syncable,syncauto},CommandData:{command:update-status,created:32 minutes ago,"Test",account:bamfic/hubzilla,itemId:4898,hashCode:1528768937,CommandResult:{executed:5, last:just now, retriesLeft:9, error:Soft}}}
        2015-11-16-21-07-56 V/MyServiceEventsReceiver: onReceive AFTER_EXECUTING_COMMAND for TimelineCursorLoader1, ins
```

It looks like "error:soft" but it doesn't tell me what the error was. Any ideas?

Cross-referencing the hubzilla error in case this may be a bug in the API there: 
https://github.com/redmatrix/hubzilla/issues/158

**Comment by yvolk** [comment]
@kenrestivo Two suggestions:
1. The operation may have more than one step,  and some "soft" error occurred at a previous one, which you didn't show in the log.
2. Maybe the server doesn't return resulted "tweet"

BTW, does it actually post a message with an attachment?

If you will not figure out a problem, please send me credentials and connection details for a test user - I will make sure that at least error reporting is more informative...

**Comment by annando** [comment]
I just tested the picture upload with AndStatus 20.5 (138) (I hope this is the version number?) and the developer branch of Friendica. It works.

Since the both systems are similar it might be an idea to compare the relevant parts - including the return values when the posting is done.

**Comment by kenrestivo** [comment]
It does not complete the post on the server side, so the failure is likely there. I am not clear on why, and there is no error reported in the server logs.

@yvolk What is the best way to securely send you credentials for a test account? Or you could create an account on hub.spaz.org; registration is open at the moment.

**Comment by yvolk** [comment]
Thank you, @kenrestivo , I created andstatus account and could connect to it via AndStatus application. Will test posting later...

**Comment by yvolk** [comment]
My first posting test (even without an attachment ) showed a cause of the problem:
In the response to posting command your server returns the same message twice:
One time - at the outer level, 
and another - inside an author's record. 
This confuses AndStatus and it fails to add one of these messages to a database. This is why the whole Send action is treated as a failure. 

I will fix AndStatus anyway, but I urge you to remove the second copy from the response. 

Another observation:  "following" attribute of a user is set incorrectly: it should show if me ("authenticated user") is following that user. In AndStatus code:
```
if (!jso.isNull("following")) {
            user.followedByActor = TriState.fromBoolean(jso.optBoolean("following"));
  }
```

**Comment by kenrestivo** [comment]
Thanks for your help! I've put your note in the Hubzilla bug tracker at https://github.com/redmatrix/hubzilla/issues/158 . If I get time soon I'll fix it, otherwise others on the project might fix it.

Thanks again!

**Comment by redmatrix** [comment]
Sorry, late to the party and just saw this. The send of direct messages in hubzilla is fixed. There is no reply ability because (as noted in other issues) the Twitter API doesn't provide a parameter for declaring the parent message. We could probably work out a convention between Hubzilla, Friendica and GNU-social to provide this.

The media upload ability in Hubzilla is based on an independent hack from long before such an ability was present in Twitter. I believe there is a standard for it in Twitter now and we should just implement that. I believe Friendica already has; but we can't legally copy their code because of license incompatibilities. 

There are some minor issues for Hubzilla response formats; especially where there is no direct mapping between Twitter functionality and hubzilla functionality. And there are a few bugs. 

Most of the time we just have to give a fake answer that makes clients happy. We have no concept of followers or friends. So we just have to create a mapping of connections with permission settings which sort of imply a follower relationship. Most of the time these are not fatal errors, but it's a trade-off we make for trying to map to an API designed for a centralised social network tool and micro-blogging service like Twitter. StatusNet had to "bend the rules" to make the Twitter API work in a decentralised environment. We have to bend those rules much further because we're not only decentralised, but nomadic. Identity is not bound to DNS unlike GNU-social and Friendica. It is abstract and mobile. Relationships are also abstract. They are just collections of permissions. It's possible to communicate with folks that you have no relationship with, just as it's possible to have a mutual "relationship" and not be permitted to communicate. There is simply no way to represent these concepts accurately and unambiguously in the Twitter API so we have to strive for a balance that is "good enough for most people".

**Comment by kenrestivo** [comment]
@yvolk It seems there are a few problems with AndStatus:

1. It uploads images with an invalid MIME type (image/jpg is not legal; image/jpeg is correct)
2. It doesn't upload media in an array, as required by the Twitter spec
3. It uses update.json which is incorrect/improper, not update_with_media.json  which is correct.

Right now it looks like Hubzilla will work around these but, if you concur with these, it would be better if they could be fixed in AndStatus.

**Comment by yvolk** [comment]
@kenrestivo Thanks for spotting incorrect MIME type.
Regarding uploading images, AndStatus does use update_with_media but only in Twitter API v.1.1 (i.e. when you select "Twitter" as a type of a Social network ). "GNU Social" type is based on the Twitter API 1.0, and  so it uses some older specification  (which is not available at Twitter site already).
So I don't see any incorrectness here.
?!

**Comment by annando** [comment]
I have to second @yvolk: If he would change that then you couldn't upload pictures to any GNU Social server any more.

**Comment by redmatrix** [comment]
That's fine. statuses/update_with_media is also deprecated, and there was no way to upload status with media in the Twitter 1.0 spec - so as long as we're making up a specification to work with, let's just find something everybody agrees on.  We also implemented the 1.1 deprecated Twitter function, because that's the only thing I could find a spec for. 

[I think the Friendica implementation is incorrect for statuses/update_with_media (which takes a media array), though the single media parameter supplied in statuses/update probably works with GNU-social and andstatus.] We've now implemented both flavours so should work with most everything except new Twitter clients.  

The recent Twitter API has a separate file upload facility with chunked upload ability, and you reference the returned IDs from those functions in a status update. We probably won't be implementing that in hubzilla as we have our own file/media API now; so these older functions are provided solely to find common ground with existing third-party clients.

**Comment by yvolk** [comment]
I agree that fixing API for which we don't even have documentation,  is not a good way.
Maybe we should try to implement Hubzilla support based on Twitter API 1.1, which is at least documented and a client app may be tested with real Twitter
...but for community based federation I would turn to pump.io API (Activity Streams...). It has a potential to create globally unique identities for users and content,  uniting all social networking systems. Look, in AndStatus ALL pump.io servers fit into one "Social network" entry!

**Comment by kenrestivo** [comment]
The last mention of Activity Streams and federation between the various projects, was in the context of a spectacular flamewar between the Hubzilla, pump.io, Disapora, and StatusNet developers.

It would be nice if there were standards, but I don't see any hope of that happening soon. In the meantime, I think we'll have to rely upon a patchwork of interoperability hacks.

**Comment by rodneyrod** [comment]
@yvolk So what would you say is a benefit of pump.io compared to StatusNet, considering more people use the latter even though it's the older standard.

**Comment by yvolk** [comment]
@rodneyrod I'm not an expert in Pump.io but it seems to me that it could be better for creation of some closed network of hosts, where all participants know each other and "discovery" is not needed (or this discovery is provided by other means...) 
But Pump.io doesn't have any new releases for two years already! We have to wait and see if recent development activity can prove that Pump.io is not dead https://github.com/e14n/pump.io/graphs/contributors

**Comment by rodneyrod** [comment]
Hey, I tried signing into a Hubzilla instance recently and ran into problems.
I was able to login by setting up the server as a GNU Social type, but after it syncs it's able to pull the account name and the profile picture but no posts.

The only 'post' that shows is some temporary status that looks like a glitch.

**Comment by yvolk** [comment]
Hi @rodneyrod As two years passed since our previous discussion here, it looks now that ActivityPub specification is the way to go for Server-to-Client API unification.
Many Social Networks declared support of Server-to-Server ActivityPub protocol, but I don't know any that implemented Server-to-Client protocol, so I could adapt AndStatus to it.

**Comment by rodneyrod** [comment]
@yvolk That's a great idea. Not sure how much work needs to be done to stabilise the API for server-client communication, but in theory that sounds easier to unify around a common standard than bending Hubzilla into a limited Twitter-like API like they do currently.
Hopefully it would also mean a common client interface for Mastodon, GNU Social and Plemora too.

**Comment by csolisr** [comment]
In that regard I'm also having issues with logging into AndStatus. Namely a 401 error caused by:.

    Caused by org.json.JSONException: Value This of type java.lang.String cannot be converted to JSONObject

**Comment by yvolk** [comment]
@csolisr It's vice versa: the 401 error, that a server returned instead of JSON-formatted response, caused that "JSONException" :-)

**Comment by csolisr** [comment]
My instance is supported by the [Yunohost](https://www.yunohost.org) framework, that automatically configures an LDAP-based SSO login system. Could it be that it's interfering with the functionality of AndStatus? In that case, should I open the bug here or with the framework's issue tracker?

**Comment by yvolk** [comment]
@csolisr I think the error is simply a manifestation of the Hubzilla's incompatibility with "the Twitter and GNUSocial APIs" implemented in AndStatus. I don't know, if the problem is easily fixable or not: Hubzilla developers' help is needed to figure this out... As discussed recently, we better not fix outdated APIs but move to ActivityPub server-to-client implementation.
Waiting for any team to do this...

**Comment by redmatrix** [comment]
AndStatus works fine with Hubzilla. There may be small issues, but the basic functionality is present and working. I did a quick test a couple of weeks ago to see if it had regressed, but no - it still works. 

You must enable the twitter_api **addon** on the Hubzilla side. You must select a GNU-Social network on the AndStatus side.

LDAP authentication *might* be an issue. This was presumably fixed in the dev branch in early May 2018 (a couple of months ago) but the fix is untested as the person requesting the fix would not run on their production server on the dev branch, even for a few minutes to try it. I do not have an LDAP infrastructure to test against, and only relying on the fact that the fix appears to be correct and nothing else breaks.  The fix is included in the 3.6RC (release candidate) which is currently being tested. It is not present in 3.4.x (current master branch). I do not know how long it will take after a release for that code to make it onto the Yunohost platform. If this is important to you, it's pretty easy to clone your channel onto a site with more up-to-date code and try it. You can either keep the clone and use it for AndStatus and a channel backup, or discard it once Yunohost has the authentication fix installed and tested. My worry is that with nobody to actually test the fix before it is released, if there are continuing problems with LDAP, it may need to wait for another release cycle after that.

**Comment by csolisr** [comment]
Since I have a single-user server, I can try manually updating to the Git version to test. I'll attempt to communicate the results later.

**Comment by csolisr** [comment]
Progress update: the client works almost flawlessly after updating to 3.6 (twitter_api had been previously enabled).

**Comment by rodneyrod** [comment]
@redmatrix Found out the Twitter API plugin my server has is at 1.0

I was able to get some response from the server in Andstatus.
I got some old notifications for a couple of posts people replied to but other than that nothing.

**Comment by Mannshoch** [comment]
what's the current status?
