### ISSUE TITLE
Invalid or malformed links in messages crash AndStatus 

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#300]
A clickable link in AndStatus UI is constructed by Android builtin "linkify" function. When a User clicks the link, this is Android system, which decides, what to do and which crashes technically inside AndStatus application. So this is Android system design issue, I think. 
Saying above, I will try to modify the code to intercept and hide the exception from a User.

Examples of links and stack traces:
```
STACK_TRACE=android.content.ActivityNotFoundException: No Activity found to handle Intent {
act=android.intent.action.VIEW 
dat=/press-release/nasa-confirms-evidence-that-liquid-water-flows-on-today-s-mars/ (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
        at android.app.Activity.startActivityForResult(Activity.java:3745)
```
Another one:
```
STACK_TRACE=android.content.ActivityNotFoundException: No Activity found to handle Intent {
act=android.intent.action.VIEW 
dat=feed://radio.spaz.org/archives.xml (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
        at android.app.Activity.startActivityForResult(Activity.java:3424)
```

**Comment by yvolk** [comment]
Possible solution is here:
http://stackoverflow.com/questions/26617738/android-content-activitynotfoundexception-when-link-does-not-contain-http?lq=1

**Comment by kenrestivo** [comment]
It'd be cool if it was able to, in java-ish pseudocode:
```java
try { intent(....)} catch { toast("No activity to handle link");}
```

**Comment by yvolk** [comment]
@kenrestivo I agree, User needs to have a feedback. Not simply a link,  which cannot be clicked for an unknown reason. 

BTW: Today I received a crash report, where https link caused the same crash  (but started to work properly later, as a user wrote...)

**Comment by yvolk** [comment]
I fixed this crash, but it appeared that all 3 emulators, on which I tested this, didn't throw such exceptions (Android 4.1, 4.4 and 5.1). This means that actually the problem is specific to some vendor's firmware and is (mostly) fixed in stock Android firmware.

**Comment by yvolk** [comment]
AndStatus v.19.3 is available at the Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app
In this release: fixed crash while clicking on Invalid or malformed links in messages.

**Comment by kenrestivo** [comment]
Great! The firmware I experienced the crash on was Cyanogenmod 10 with NO google apps installed. I did not have any feedrunner/podcatcher software installed. Perhaps there's some app in the proprietary google apps which handles those intents for URLs like feed: and such, and I don't have it.

**Comment by yvolk** [comment]
@kenrestivo I just checked: All three emulators, which I used for this test, don't have Google API, i.e. they are pure Android...

**Comment by yvolk** [comment]
I see that I missed something, need to improve the fix a bit
```
USER_COMMENT=I followed a web link.
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=22.18
BRAND=motorola
PHONE_MODEL=XT1032
CUSTOM_DATA=
STACK_TRACE=android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=gopher://gopher.metafilter.com/ (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1723)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
at android.app.Activity.startActivityForResult(Activity.java:3436)
at android.app.Activity.startActivityForResult(Activity.java:3393)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
at android.app.Activity.startActivity(Activity.java:3644)
at android.app.Activity.startActivity(Activity.java:3607)
at android.text.style.URLSpan.onClick(URLSpan.java:62)
at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
at android.widget.TextView.onTouchEvent(TextView.java:7724)
```

**Comment by yvolk** [comment]
Fixed in v.23.01
