### ISSUE TITLE
IndexOutOfBoundsException at android.text.PackedIntVector.getValue

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#334]
As I found out reading this 
https://www.reddit.com/r/redditisfun/comments/3spyhw/crash_on_special_case_reddit_post/
and this: https://github.com/robolectric/robolectric/issues/2286 - this is a bug of Android API 23 devices, which occurs on showing e.g. '\u00AD' "soft hyphen" or, as reported, other 0-length Unicode characters...

I reproduced this bug on my device. We need to reproduce this in a test suite first...

```
USER_COMMENT=
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=22.13
BRAND=google
PHONE_MODEL=Nexus 5X
CUSTOM_DATA=
STACK_TRACE=java.lang.IndexOutOfBoundsException: 1, 0
at android.text.PackedIntVector.getValue(PackedIntVector.java:71)
at android.text.DynamicLayout.getLineStart(DynamicLayout.java:612)
at android.text.Layout.drawText(Layout.java:286)
```

**Comment by yvolk** [comment]
I reproduced the bug in a TestSuite, and it appeared that this line causes the crash if a text contains the "soft hyphen" (  '\u00AD' ) only:
```
textView.setMovementMethod(LinkMovementMethod.getInstance())
```
I fixed this by replacing that "soft hyphen" with "-" ("minus" sign) before displaying to a User.

**Comment by yvolk** [comment]
Fixed in v.22.17
