### ISSUE TITLE
AndStatus crashes when I try to view an item from a search

### ISSUE THREAD

**Issue by schumaml** [andstatus/andstatus#405]
Hi, 

whenever I try to view a search result of a global search, And status crashes.

The crash report is as follows:

USER_COMMENT=tried to open a tweet from a global search
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=27.04
BRAND=samsung
PHONE_MODEL=SM-G800F
CUSTOM_DATA=
STACK_TRACE=android.content.ActivityNotFoundException: No Activity found to handle Intent { act=org.andstatus.app.action.VIEW_CONVERSATION dat=content://org.andstatus.app.data.MyProvider/msg/0/lt/search/origin/1/user/0/search/foobar/item/120841 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1861)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
	at android.app.Activity.startActivityForResult(Activity.java:4091)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
	at android.app.Activity.startActivityForResult(Activity.java:4038)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
	at org.andstatus.app.msg.TimelineActivity.startActivityForResult(TimelineActivity.java:956)
	at android.app.Activity.startActivity(Activity.java:4362)
	at android.app.Activity.startActivity(Activity.java:4330)
	at org.andstatus.app.msg.TimelineActivity.onItemClick(TimelineActivity.java:510)
	at org.andstatus.app.msg.TimelineAdapter.onClick(TimelineAdapter.java:261)
	at android.view.View.performClick(View.java:5242)
	at android.view.View$PerformClick.run(View.java:21196)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by yvolk** [comment]
@schumaml Could you please clarify what exactly you do and when exactly the crash occurs?
So:
1. You click on "Global search button, type "foobar" and press Enter/Go... key on a keyboard.
2. AndStatus opens a "Search" timeline.
What exactly do you do further and at what step the crash occurs? (Please, more concrete than "I'm trying to open a tweet"...)

**Comment by schumaml** [comment]
I tap one of the search results to view the whole conversation, e.g. the initial tweets and its replies,  of which I had found one.

As soon as I tap, Andstatus closes and I get the crash report window with the "what did you do" entry.

**Comment by yvolk** [comment]
Q1. So you usually see the message Context menu on tapping a message?
I mean, does AndStatus crash instead opening the Context menu?
Q2. Anyway, could you open the message Context menu and select "Open Conversation" in it?!
Q3. Where did you get AndStatus package? I mean, from what source and how did you install it?

**Comment by schumaml** [comment]
I've set the "long press to open context menu" option, so I won't get this on a single tap.

When I choose Open Conversation from the menu (via long-pressing, I don't experience a crash.

I'm seeing the same behaviour on two different devices; on one of them I got And status via F-Droid, on the other via the Google Play Store.

**Comment by yvolk** [comment]
Thank you, now I easily reproduced the crash. Will no take long to fix.
**Workaround until the fix will be released: check off  ”Long press to open Context menu” in Settings -> Gestures**

**Comment by schumaml** [comment]
Nice, thanks!

**Comment by yvolk** [comment]
AndStatus v.27.05 released with the latest fixes
