### ISSUE TITLE
ANR on initializing a service

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#431]
Service should not load its command queue in the main thread.

More details:

Cmd line: org.andstatus.app
JNI: CheckJNI is off; workarounds are off; pins=0; globals=158
DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)
"main" prio=5 tid=1 TIMED_WAIT
  | group="main" sCount=1 dsCount=0 obj=0x4111ca18 self=0x57066020
  | sysTid=12154 nice=0 sched=0/0 cgrp=apps handle=1074825308
  | state=S schedstat=( 1405822144 124775074 1762 ) utm=114 stm=26 core=1
  at java.lang.Object.wait(Native Method)
  - waiting on <0x4111ce18> (a java.lang.VMThread) held by tid=1 (main)
  at java.lang.Thread.parkFor(Thread.java:1202)
  at sun.misc.Unsafe.park(Unsafe.java:323)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:199)
  at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
  at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
  at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586)
  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
  at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
  at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
  at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
  at org.andstatus.app.service.CommandQueue.load(CommandQueue.java:81)
  at org.andstatus.app.service.CommandQueue.load(CommandQueue.java:58)
  at org.andstatus.app.service.MyService.initialize(MyService.java:227)
  at org.andstatus.app.service.MyService.receiveOtherCommand(MyService.java:164)
  at org.andstatus.app.service.MyService.receiveCommand(MyService.java:152)
  at org.andstatus.app.service.MyService.onStartCommand(MyService.java:124)
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2824)
  at android.app.ActivityThread.access$1900(ActivityThread.java:167)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:153)
  at android.app.ActivityThread.main(ActivityThread.java:5341)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
  at dalvik.system.NativeStart.main(Native Method)

**Comment by yvolk** [comment]
Currently AndStatus loads and saves commands queue in the main thread that obviously can take too long time.
We need to do this initialization/shutting down as asynchronous tasks.
