### ISSUE TITLE
Move as much data as possible from SharedPreferences (files) to the database

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#44]
Android SharedPreferences are not reliable, especially when they maybe changed concurrently and often by different processes and threads.

I always had problems with preferences' visibility between processes (UI and a service), and recently I simply lost all my SharedProperties without any obvious reason. Thanks God my Sqlite database was never corrupted in four years.

**Comment by yvolk** [comment]
Recent info about ANRs of AndStatus show that SharedPreferences cause No-response/timeouts
See http://stackoverflow.com/questions/29166812/sharedpreferences-apply-and-anr-application
- it explains that apply() forks a thread.
So locking occurs between threads of the application.

E.g. below:
```
suspend all histogram:	Sum: 220.590ms 99% C.I. 0.020ms-70.307ms Avg: 1.586ms Max: 218.629ms
DALVIK THREADS (16):
"pool-2-thread-1" prio=5 tid=15 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x12dcdb20 self=0xb937a600
  | sysTid=26295 nice=0 cgrp=default sched=0/0 handle=0xa1f31930
  | state=R schedstat=( 9727102782 936233483 9386 ) utm=837 stm=135 core=1 HZ=100
  | stack=0xa1e2f000-0xa1e31000 stackSize=1038KB
  | held mutexes= "mutator lock"(shared held)
  at java.nio.CharBuffer.hasArray(CharBuffer.java:336)
  at java.nio.charset.CharsetEncoderICU.getArray(CharsetEncoderICU.java:213)
  at java.nio.charset.CharsetEncoderICU.encodeLoop(CharsetEncoderICU.java:162)
  at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:374)
  at com.android.internal.util.FastXmlSerializer.flush(FastXmlSerializer.java:248)
  at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:92)
  at com.android.internal.util.FastXmlSerializer.appendIndent(FastXmlSerializer.java:127)
  at com.android.internal.util.FastXmlSerializer.startTag(FastXmlSerializer.java:358)
  at com.android.internal.util.XmlUtils.writeValueXml(XmlUtils.java:651)
  at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:300)
  at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:269)
  at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:235)
  at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:192)
  at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:600)
  at android.app.SharedPreferencesImpl.-wrap2(SharedPreferencesImpl.java:-1)
  at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:515)
  - locked <0x0cd0e521> (a java.lang.Object)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

"Signal Catcher" daemon prio=5 tid=2 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x12c910a0 self=0xb8897f68
  | sysTid=26242 nice=0 cgrp=default sched=0/0 handle=0xb4566930
  | state=R schedstat=( 255720994 24279571 190 ) utm=20 stm=5 core=1 HZ=100
  | stack=0xb446a000-0xb446c000 stackSize=1014KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 0035c6d5  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+116)
  native: #01 pc 0033d7cf  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+138)
  native: #02 pc 00346e9b  /system/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+422)
  native: #03 pc 003479e3  /system/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*)+194)
  native: #04 pc 00347f09  /system/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+124)
  native: #05 pc 003485f1  /system/lib/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+312)
  native: #06 pc 00321d3d  /system/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+68)
  native: #07 pc 00328e23  /system/lib/libart.so (art::SignalCatcher::HandleSigQuit()+910)
  native: #08 pc 00329733  /system/lib/libart.so (art::SignalCatcher::Run(void*)+390)
  native: #09 pc 00041b0b  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #10 pc 00019405  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74cbd2a0 self=0xb78d6790
  | sysTid=26237 nice=0 cgrp=default sched=0/0 handle=0xb6f71b34
  | state=S schedstat=( 5152339391 931099942 4827 ) utm=474 stm=41 core=1 HZ=100
  | stack=0xbe3af000-0xbe3b1000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0347cd46> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:1220)
  - locked <0x0347cd46> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:299)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:971)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1278)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
  at android.app.SharedPreferencesImpl$EditorImpl$1.run(SharedPreferencesImpl.java:366)
  at android.app.QueuedWork.waitToFinish(QueuedWork.java:88)
  at android.app.ActivityThread.handleStopService(ActivityThread.java:3065)
  at android.app.ActivityThread.-wrap21(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1457)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5443)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by yvolk** [comment]
Recently I received several Crash reports with java.lang.OutOfMemoryError during Commands Queue saving:
```
at java.util.HashMap.makeTable(HashMap.java:569)
at java.util.HashMap.<init>(HashMap.java:158)
at java.util.HashMap.<init>(HashMap.java:195)
at android.app.SharedPreferencesImpl$EditorImpl.commitToMemory(SharedPreferencesImpl.java:400)
at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:360)
at org.andstatus.app.service.CommandData.toSharedPreferences(CommandData.java:267)
at org.andstatus.app.service.CommandData.saveQueue(CommandData.java:228)
at org.andstatus.app.service.MyService.saveState(MyService.java:585) ...
```
(all reports from Android v.4.4.4 devices though...) This gives another reason to move Commands Queues to SQLite database.
